apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  chart:
    spec:
      chart: karpenter
      version: "0.16.3"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  values:
    clusterName: ${CLUSTER_NAME}
    clusterEndpoint: ${CLUSTER_ENDPOINT}
    serviceAccount:
      create: true
      name: karpenter
      annotations:
        eks.amazonaws.com/role-arn: ${KARPENTER_ROLE_ARN}
    aws:
      defaultInstanceProfile: ${KARPENTER_INSTANCE_PROFILE}
    nodePoolConfig:
      labels:
        type: karpenter
