apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  chart:
    spec:
      chart: karpenter
      version: "0.16.3"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  values:
    settings:
      clusterName: ${CLUSTER_NAME}
      clusterEndpoint: ${CLUSTER_ENDPOINT}
      interruptionQueue: karpenter-interruption-queue
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${KARPENTER_ROLE_ARN}
    nodePoolConfig:
      labels:
        type: karpenter
