apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: gpu-operator
      version: "v23.9.1"  # Update to latest stable version as needed
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  values:
    operator:
      defaultRuntime: containerd
      runtimeClass: nvidia
      initContainer:
        image:
          repository: nvcr.io/nvidia/cloud-native/k8s-driver-manager
          tag: v0.7.0  # default at time of writing
      controller:
        manager:
          image:
            repository: nvcr.io/nvidia/cloud-native/gpu-operator
            tag: v23.9.2
      toolkit:
        enabled: false # Disable Container Toolkit installation
    validator:
      enabled: true # Need validator for device node setup
      driver:
        env:
          - name: DISABLE_DEV_CHAR_SYMLINK_CREATION
            value: "true"

    driver:
      enabled: false # Driver is preinstalled on AMI
    
    toolkit:
      enabled: false # Toolkit is preinstalled on AMI
    
    devicePlugin:
      enabled: true # Only enable the device plugin
      version: v0.13.0
    
    dcgm:
      enabled: false # Disable DCGM metrics exporter
    
    dcgmExporter:
      enabled: false # Disable DCGM Prometheus exporter
    
    gfd:
      enabled: false # Disable GPU Feature Discovery
      
    mig:
      strategy: none # MIG not needed for g4dn.xlarge
    
    nodeSelector:
      nvidia.com/gpu.present: "true"
    
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    
    podSecurityPolicy:
      enabled: false # PSPs are deprecated past 1.25
    
    securityContext:
      runAsNonRoot: false
    
    serviceAccount:
      create: true
      name: ""
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi