apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: gpu-operator
      version: "v23.9.1"  # Update to latest stable version as needed
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  values:
    operator:
      defaultRuntime: containerd
    driver:
      enabled: true
    toolkit:
      enabled: true
    devicePlugin:
      enabled: true
      config:
        name: gpu-feature-discovery
        version: v0.7.0
    validator:
      driver:
        env:
        - name: DISABLE_DEV_CHAR_SYMLINK_CREATION
          value: "true"
