apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system.yaml
  - monitoring.yaml
  - gpu-operator.yaml
  - logging.yaml
  - aws-ebs-csi.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: fullstack-ollama
