apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: "2.27.0"
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
  values:
    controller:
      region: us-east-1
      replicaCount: 1
    storageClasses:
      - name: ebs-sc
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        volumeBindingMode: WaitForFirstConsumer
        reclaimPolicy: Delete
        parameters:
          type: gp3
          encrypted: "true"
