apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml

patches:
  - path: patch-role-arn.yaml
    target:
      kind: HelmRelease
      name: aws-ebs-csi-driver

replacements:
  - source:
      kind: ConfigMap
      name: terraform-outputs
      namespace: kube-system
    targets:
      - select:
          kind: HelmRelease
          name: aws-ebs-csi-driver
        fieldPaths:
          - spec.values.controller.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          - spec.values.node.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        options:
          create: true
          delimiter: ${}
    sourceRef:
      apiVersion: v1
      kind: ConfigMap
      name: terraform-outputs
      namespace: kube-system
      fieldPath: data.EBS_CSI_ROLE_ARN
