apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: logging
type: Opaque
data:
  # Default password is 'elastic' - you should change this in production
  password: ZWxhc3RpYw==  # base64 encoded 'elastic'
